import smtplib
from email.message import EmailMessage


SMTP_HOST = "localhost"
SMTP_PORT = 1025


def main():
    message = EmailMessage()

    message["From"] = "automation@evalytics.test"
    message["To"] = "tenant01@evalytics.test"
    message["Subject"] = "Evalytics Automation Test"

    message.set_content(
        "This is the first automated email generated by "
        "the Evalytics AI Tester framework."
    )

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as smtp:
        smtp.send_message(message)

    print("Email successfully sent to Mailpit.")


if __name__ == "__main__":
    main()